// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_tipo_inscricao_nao_selecionado', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_tipo_inscricao_nao_selecionado', async function() {
    await driver.get("http://localhost:8081/adicionar/evento")
    await driver.manage().window().setRect(1118, 776)
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).sendKeys("Apenas Um Evento")
    await driver.findElement(By.name("participantes_esperados")).click()
    await driver.findElement(By.name("participantes_esperados")).sendKeys("100")
    await driver.findElement(By.id("quantSalas")).click()
    await driver.findElement(By.id("quantSalas")).sendKeys("10")
    await driver.findElement(By.name("local_evento")).click()
    await driver.findElement(By.name("local_evento")).click()
    await driver.findElement(By.name("local_evento")).sendKeys("IFPI - Piripiri")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2020-01-20")
    await driver.findElement(By.name("data_termino")).click()
    await driver.findElement(By.name("data_termino")).sendKeys("2020-01-24")
    await driver.findElement(By.css("div:nth-child(8)")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".letrasespac")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nSelecione Gratuito ou Pago")
  })
})
