// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_quantidade_salas_menor_1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_quantidade_salas_menor_1', async function() {
    await driver.get("http://localhost:8081/adicionar/evento")
    await driver.manage().window().setRect(1118, 776)
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).sendKeys("Um Evento Legal")
    await driver.findElement(By.name("participantes_esperados")).click()
    await driver.findElement(By.name("participantes_esperados")).sendKeys("100")
    await driver.findElement(By.id("quantSalas")).click()
    await driver.findElement(By.id("quantSalas")).sendKeys("-1")
    await driver.findElement(By.id("quantSalas")).sendKeys("-1")
    await driver.findElement(By.id("quantSalas")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("quantSalas")).sendKeys("-2")
    await driver.findElement(By.id("quantSalas")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("quantSalas")).sendKeys("-3")
    await driver.findElement(By.id("quantSalas")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("quantSalas")).sendKeys("-4")
    await driver.findElement(By.id("quantSalas")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("quantSalas")).sendKeys("-5")
    await driver.findElement(By.name("local_evento")).click()
    await driver.findElement(By.name("local_evento")).click()
    await driver.findElement(By.name("local_evento")).sendKeys("Konoha")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2020-01-20")
    await driver.findElement(By.name("data_termino")).click()
    await driver.findElement(By.name("data_termino")).sendKeys("2020-01-24")
    {
      const element = await driver.findElement(By.id("eventoTipo"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("eventoTipo"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("eventoTipo"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("eventoTipo")).click()
    {
      const dropdown = await driver.findElement(By.id("eventoTipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Gratuita']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css("h1")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nQuantidade de Salas")
  })
})
