// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_campos_vazios', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_campos_vazios', async function() {
    await driver.get("http://localhost:8081/adicionar/evento")
    await driver.manage().window().setRect(1118, 776)
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.name("participantes_esperados")).click()
    await driver.findElement(By.id("quantSalas")).click()
    await driver.findElement(By.name("local_evento")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".letrasespac > .container")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nNome do Evento, Número de Participantes, Quantidade de Salas, Local do Evento , Data de Inicio, Data de Termino, Selecione Gratuito ou Pago")
  })
})
