// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_numero_participantes_menor_1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_numero_participantes_menor_1', async function() {
    await driver.get("http://localhost:8081/adicionar/evento")
    await driver.manage().window().setRect(1118, 776)
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).sendKeys("Um Evento")
    await driver.findElement(By.css(".container:nth-child(6) > .row")).click()
    await driver.findElement(By.name("participantes_esperados")).click()
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-1")
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-1")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-2")
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-2")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-3")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-4")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-5")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-6")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-7")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-8")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-9")
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-9")
    await driver.findElement(By.name("participantes_esperados")).sendKeys(Key.DOWN)
    await driver.findElement(By.name("participantes_esperados")).sendKeys("-10")
    await driver.findElement(By.id("quantSalas")).click()
    await driver.findElement(By.id("quantSalas")).sendKeys("10")
    await driver.findElement(By.name("local_evento")).click()
    {
      const element = await driver.findElement(By.name("local_evento"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.name("local_evento")).sendKeys("IFPI - Piripiri")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2020-01-21")
    await driver.findElement(By.name("data_termino")).click()
    await driver.findElement(By.name("data_termino")).sendKeys("2020-01-24")
    await driver.findElement(By.id("eventoTipo")).click()
    {
      const dropdown = await driver.findElement(By.id("eventoTipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Gratuita']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nNúmero de Participantes")
  })
})
