// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_nome_ministrante_menor_2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_nome_ministrante_menor_2', async function() {
    await driver.get("http://localhost:8081/adicionar/ministrantes/10")
    await driver.manage().window().setRect(1227, 784)
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).click()
    await driver.findElement(By.id("nome")).sendKeys("A")
    await driver.findElement(By.css(".row:nth-child(1)")).click()
    await driver.findElement(By.name("contato")).click()
    await driver.findElement(By.name("contato")).click()
    await driver.findElement(By.name("contato")).click()
    await driver.findElement(By.name("contato")).sendKeys("(086) 9977-5678")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("alguma@gmail.com")
    await driver.findElement(By.id("text")).click()
    await driver.findElement(By.id("text")).sendKeys("Ensino Médio")
    await driver.findElement(By.css("center:nth-child(5)")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nNome")
  })
})
