// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_campos_vazios', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_campos_vazios', async function() {
    await driver.get("http://localhost:8081/adicionar/ministrantes/10")
    await driver.manage().window().setRect(1227, 784)
    await driver.findElement(By.css(".mt-2")).click()
    await driver.findElement(By.css(".mt-2")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css("h1")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nNome, Telefone, Email, Formação")
  })
})
