// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_desconto_nao_selecionado', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_desconto_nao_selecionado', async function() {
    await driver.get("http://localhost:8081/adicionar/cupons/10")
    await driver.manage().window().setRect(1118, 776)
    await driver.findElement(By.name("codigo")).click()
    await driver.findElement(By.name("codigo")).click()
    await driver.findElement(By.name("codigo")).click()
    await driver.findElement(By.name("codigo")).sendKeys("ABC123")
    await driver.findElement(By.id("desconto")).click()
    await driver.findElement(By.id("desconto")).click()
    await driver.findElement(By.id("quantidade")).click()
    await driver.findElement(By.id("quantidade")).sendKeys("10")
    await driver.findElement(By.id("validade")).click()
    await driver.findElement(By.id("validade")).sendKeys("2020-01-20")
    await driver.findElement(By.css(".mt-2")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.close()
  })
})
