// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_estado_nao_selecionado', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_estado_nao_selecionado', async function() {
    await driver.get("http://localhost:8081/cadastroAdm")
    await driver.manage().window().setRect(1284, 812)
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    await driver.findElement(By.name("nome")).click()
    await driver.findElement(By.name("nome")).sendKeys("Bruno Cruz")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("bruno@gmail.com")
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    await driver.findElement(By.name("senha")).click()
    await driver.findElement(By.name("senha")).sendKeys("123456789")
    await driver.findElement(By.name("senha2")).click()
    await driver.findElement(By.name("senha2")).sendKeys("123456789")
    await driver.findElement(By.css("center:nth-child(7)")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "Selecione um estado")
  })
})
