// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_comparando_senhas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_comparando_senhas', async function() {
    await driver.get("http://localhost:8081/cadastroAdm")
    await driver.manage().window().setRect(1075, 692)
    await driver.findElement(By.css(".mt-2")).click()
    await driver.findElement(By.css(".mt-2")).click()
    await driver.findElement(By.name("nome")).click()
    await driver.findElement(By.name("nome")).sendKeys("Bruno Cruz")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("robo@gmail.com")
    await driver.findElement(By.name("senha")).click()
    await driver.findElement(By.name("senha")).sendKeys("1q2w3e4r5t6y")
    await driver.findElement(By.name("senha2")).click()
    await driver.findElement(By.name("senha2")).sendKeys("gtfrdeswqagy")
    {
      const element = await driver.findElement(By.name("estado"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("estado"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("estado"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("estado")).click()
    {
      const dropdown = await driver.findElement(By.name("estado"))
      await dropdown.findElement(By.xpath("//option[. = 'Piauí']")).click()
    }
    await driver.findElement(By.css("option:nth-child(4)")).click()
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".form-grup")).click()
    await driver.findElement(By.css(".alert")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "ERRO!\\\\nSenha")
  })
})
