// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_campos_vazios', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_campos_vazios', async function() {
    await driver.get("http://localhost:8081/cadastroAdm")
    await driver.manage().window().setRect(1284, 812)
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    await driver.findElement(By.css(".col-xs-8")).click()
    await driver.findElement(By.css(".col-xs-8")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".container:nth-child(4) > .row")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "Preencha todos os campos")
  })
})
