// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_login_concluido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_login_concluido', async function() {
    await driver.get("http://localhost:8081/login")
    await driver.manage().window().setRect(1024, 712)
    await driver.findElement(By.id("e-mail")).click()
    await driver.findElement(By.name("senha")).sendKeys("12345678")
    await driver.findElement(By.id("e-mail")).sendKeys("brunim@gmail.com")
    await driver.findElement(By.name("senha")).click()
    await driver.findElement(By.id("e-mail")).click()
    await driver.findElement(By.name("senha")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".card:nth-child(3) > .card-body")).click()
    await driver.close()
  })
})
