// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('teste_senha_menor_8', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('teste_senha_menor_8', async function() {
    await driver.get("http://localhost:8081/login")
    await driver.manage().window().setRect(1080, 684)
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.css(".letrasespac")).click()
    await driver.findElement(By.id("e-mail")).click()
    await driver.findElement(By.id("e-mail")).sendKeys("brunim@gmail.com")
    await driver.findElement(By.css(".col-sm-8")).click()
    await driver.findElement(By.name("senha")).click()
    await driver.findElement(By.name("senha")).sendKeys("123")
    await driver.findElement(By.css("center:nth-child(2) > div")).click()
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    await driver.findElement(By.css(".alert")).click()
    await driver.findElement(By.css(".col-xs-8 center:nth-child(1)")).click()
    await driver.findElement(By.css(".col-xs-8 center:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".col-xs-8 center:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    assert(await driver.findElement(By.css(".alert")).getText() == "Senha inválido")
  })
})
